from __future__ import annotations


def normalize_genre(raw: str) -> str:
    genre = raw.lower().strip().replace("&", "and")
    genre = genre.replace("/", " ").replace("_", " ")
    genre = " ".join(genre.split())

    rules = [
        # Music genres 
        ("pop", "pop"),
        ("k-pop", "pop"),
        ("j-pop", "pop"),
        ("power-pop", "pop"),
        ("synth-pop", "pop"),
        ("indie pop", "pop"),
        ("rock", "rock"),
        ("hard-rock", "rock"),
        ("punk-rock", "rock"),
        ("punk", "rock"),
        ("emo", "rock"),
        ("metal", "rock"),
        ("hardcore", "rock"),
        ("grunge", "rock"),
        ("alternative", "rock"),
        ("hip hop", "hip-hop"),
        ("hip-hop", "hip-hop"),
        ("rap", "hip-hop"),
        ("trap", "hip-hop"),
        ("r&b", "rnb"),
        ("rnb", "rnb"),
        ("rhythm and blues", "rnb"),
        ("soul", "rnb"),
        ("funk", "rnb"),
        ("country", "country"),
        ("bluegrass", "country"),
        ("americana", "country"),
        ("jazz", "jazz"),
        ("blues", "jazz"),
        ("swing", "jazz"),
        ("classical", "classical"),
        ("piano", "classical"),
        ("orchestra", "classical"),
        ("opera", "classical"),
        ("ambient", "classical"),
        ("electronic", "electronic"),
        ("dance", "electronic"),
        ("edm", "electronic"),
        ("techno", "electronic"),
        ("house", "electronic"),
        ("electro", "electronic"),
        ("deep-house", "electronic"),
        ("progressive-house", "electronic"),
        ("chicago-house", "electronic"),
        ("j-dance", "electronic"),
        ("indie", "indie"),
        ("singer-songwriter", "indie"),
        ("songwriter", "indie"),
        ("folk", "indie"),
        ("acoustic", "indie"),
        ("latin", "latin"),
        ("salsa", "latin"),
        ("brazil", "latin"),
        ("spanish", "latin"),
        ("reggae", "latin"),
        ("ska", "latin"),
        ("bossa nova", "latin"),
        ("industrial", "electronic"),
        ("groove", "rnb"),

        # Music --> content crosswalk (bridges music to podcast/book genres) (was missing before EDA)
        ("hip-hop", "society-culture"),   # hip-hop culture is heavily discussed in podcasts
        ("rnb", "society-culture"),
        ("soul", "society-culture"),
        ("jazz", "history"),              # jazz history is a major podcast/book genre
        ("blues", "history"),
        ("classical", "education"),       # classical music education
        ("folk", "history"),
        ("country", "society-culture"),
        ("indie", "society-culture"),
        ("rock", "society-culture"),
        ("pop", "society-culture"),
        ("electronic", "technology"),     # electronic music production → technology
        ("latin", "society-culture"),

        # Podcast genres 
        ("news", "news"),
        ("comedy", "comedy"),
        ("business", "business"),
        ("entrepreneur", "business"),
        ("finance", "business"),
        ("investing", "business"),
        ("education", "education"),
        ("learning", "education"),
        ("courses", "education"),
        ("history", "history"),
        ("health", "health"),
        ("fitness", "health"),
        ("wellness", "health"),
        ("medicine", "health"),
        ("mental health", "health"),
        ("science", "science"),
        ("technology", "technology"),
        ("tech", "technology"),
        ("society", "society-culture"),
        ("culture", "society-culture"),
        ("music commentary", "society-culture"),
        ("music history", "history"),
        ("music interviews", "society-culture"),
        ("entertainment", "society-culture"),
        ("tv and film", "society-culture"),
        ("film reviews", "society-culture"),
        ("relationships", "psychology"),
        ("self-help", "self-help"),
        ("self help", "self-help"),
        ("personal growth", "self-help"),
        ("motivation", "self-help"),
        ("psychology", "psychology"),
        ("philosophy", "psychology"),
        ("religion", "society-culture"),
        ("spirituality", "society-culture"),
        ("christianity", "society-culture"),
        ("language learning", "education"),
        ("video games", "technology"),
        ("sports", "health"),
        ("true crime", "mystery"),

        # Book genres 
        ("biography", "biography"),
        ("memoir", "biography"),
        ("autobiography", "biography"),
        ("fiction", "fiction"),
        ("literary fiction", "fiction"),
        ("english fiction", "fiction"),
        ("american literature", "fiction"),
        ("persian literature", "fiction"),
        ("young adult", "fiction"),
        ("children", "fiction"),
        ("fantasy", "fantasy"),
        ("science fiction", "science"),
        ("mystery", "mystery"),
        ("thriller", "thriller"),
        ("crime", "mystery"),
        ("romance", "romance"),
        ("horror", "mystery"),
        ("subject headings", "education"),
        ("library of congress", "education"),
        ("charitable uses", "business"),
        ("electronic journals", "science"),
        ("universalism", "psychology"),
        ("hadlyme", "history"),
        ("florida", "history"),
        ("australia", "history"),
        ("great britain", "history"),
    ]

    for needle, normalized in rules:
        if needle in genre:
            return normalized
    return genre


def normalize_genres(genres: list[str]) -> list[str]:
    cleaned = [normalize_genre(g) for g in genres if g and g.strip()]
    return sorted(set(cleaned))