"""Single source of truth for all modal configuration.

All modal IDs, dimensions, factory functions, and dependencies are defined here.
Derived values (button_id, modal_id, etc.) are generated by get_modal_ids() and
get_modal_buttons() so there is no duplicate config (e.g. no separate modal_registry).
"""

MODAL_CONFIGS = {
	'songs': {
		'title': 'Spotify Tracks Explorer',
		'factory': 'create_songs_modal',
		'module': 'components.songs_modal',
		'dependencies': ['table_df', 'artist_options', 'pop_min', 'pop_max'],
		'width': '85%',
		'max_width': '950px',
		'button_label': 'Browse Spotify Tracks',
	},
	'users': {
		'title': 'Users & Friends Explorer',
		'factory': 'create_users_modal',
		'module': 'components.users_modal',
		'dependencies': ['user_options', 'initial_histogram'],
		'width': '88%',
		'max_width': '1250px',
		'button_label': 'Explore Users & Friends',
	},
	'user_favorites': {
		'title': 'User Favorite Songs',
		'factory': 'create_user_favorites_modal',
		'module': 'components.user_favorites_modal',
		'dependencies': ['user_options'],
		'width': '80%',
		'max_width': '1000px',
		'button_label': 'User Favorite Songs',
	},
	'genre_artist': {
		'title': 'Browse by Genre & Artist',
		'factory': 'create_genre_artist_modal',
		'module': 'components.genre_artist_modal',
		'dependencies': ['genre_options'],
		'width': '85%',
		'max_width': '1100px',
		'button_label': 'Browse by Genre & Artist',
	},
	'friends_popular_songs': {
		'title': 'Popular Songs Among Friends',
		'factory': 'create_friends_popular_songs_modal',
		'module': 'components.friends_popular_songs_modal',
		'dependencies': ['user_options'],
		'width': '80%',
		'max_width': '900px',
		'button_label': 'Popular Songs Among Friends',
	},
	'friends_top_genres': {
		'title': 'Top Genres Among Friends',
		'factory': 'create_friends_top_genres_modal',
		'module': 'components.friends_top_genres_modal',
		'dependencies': ['user_options'],
		'width': '80%',
		'max_width': '900px',
		'button_label': 'Top Genres Among Friends',
	},
	'top_songs_per_genre': {
		'title': 'Top Songs Per Genre',
		'factory': 'create_top_songs_per_genre_modal',
		'module': 'components.top_songs_per_genre_modal',
		'dependencies': ['genre_options'],
		'width': '85%',
		'max_width': '1000px',
		'button_label': 'Top Songs per Genre',
	},
	'recommendations': {
		'title': 'Friend-Based Recommendations',
		'factory': 'create_recommendations_modal',
		'module': 'components.recommendations_modal',
		'dependencies': ['user_options'],
		'width': '80%',
		'max_width': '1000px',
		'button_label': 'Friend-Based Recommendations',
	},
	'friend_artists': {
		'title': 'Top Artists Among Friends',
		'factory': 'create_friend_artists_modal',
		'module': 'components.friend_artists_modal',
		'dependencies': ['user_options'],
		'width': '75%',
		'max_width': '900px',
		'button_label': 'Top Artists Among Friends',
	},
	'genre_overlap': {
		'title': 'Genre Overlap Between Users',
		'factory': 'create_genre_overlap_modal',
		'module': 'components.genre_overlap_modal',
		'dependencies': [],  # No dependencies
		'width': '85%',
		'max_width': '1100px',
		'button_label': 'Genre Overlap Between Users',
	},
	'itunes_comparison': {
		'title': 'iTunes vs Spotify Artists',
		'factory': 'create_itunes_comparison_modal',
		'module': 'components.itunes_comparison_modal',
		'dependencies': [],  # No initial dependencies, loads on button click
		'width': '90%',
		'max_width': '1400px',
		'button_label': 'iTunes vs Spotify Artists',
	},
	'billboard': {
		'title': 'Billboard Hot 100 in Spotify',
		'factory': 'create_billboard_modal',
		'module': 'components.billboard_modal',
		'dependencies': [],  # No initial dependencies, loads on button click
		'width': '90%',
		'max_width': '1400px',
		'button_label': 'Billboard Hot 100 in Spotify',
	}
}


def get_modal_keys():
	"""Get list of all modal keys."""
	return list(MODAL_CONFIGS.keys())


def get_modal_config(modal_key):
	"""Get configuration for a specific modal."""
	return MODAL_CONFIGS.get(modal_key)


def get_modal_buttons():
	"""Generate button definitions from modal configurations."""
	buttons = []
	for key, config in MODAL_CONFIGS.items():
		button_id = f'open-{key.replace("_", "-")}-modal'
		button_label = config['button_label']
		buttons.append((button_id, button_label))
	return buttons


def get_modal_ids(modal_key):
	"""Generate standard IDs for a modal."""
	key_with_dashes = modal_key.replace('_', '-')
	return {
		'modal_id': f'{key_with_dashes}-modal',
		'backdrop_id': f'{key_with_dashes}-modal-backdrop',
		'button_id': f'open-{key_with_dashes}-modal',
		'close_button_id': f'close-{key_with_dashes}-modal',
	}


def get_modal_dimensions():
	"""Get dimensions configuration for all modals."""
	return {
		key: (config['width'], config['max_width'])
		for key, config in MODAL_CONFIGS.items()
	}
